
SELECT COUNT(*) AS BROJ FROM AERODROMI_LETOVI;

SELECT COUNT(*) AS BROJ FROM AERODROMI_LETOVI WHERE AKTIVAN = TRUE;

SELECT * FROM AERODROMI_LETOVI WHERE ICAO IN ('EBBR', 'EDDF', 'EDDM', 'EGGP', 'EGLL', 'EIDW', 'EPWA', 'GCLP', 'HEGN', 'LDZA', 'LEBL', 'LEPA', 'LFPG', 'EDDS', 'LIPZ', 'LOWW', 'LTBJ', 'LSZH', 'LJLJ', 'OMDB');

SELECT COUNT(*) AS BROJ_PODATAKA FROM LETOVI_POLASCI;
--5.11.2022 do 15.11.2022.
SELECT * FROM LETOVI_POLASCI WHERE FIRSTSEEN BETWEEN 1667606400 AND 1668556799;

SELECT CAST(STORED AS DATE) AS "Date", COUNT(*) AS BROJPODATAKA FROM LETOVI_POLASCI GROUP BY CAST(STORED AS DATE)
ORDER BY CAST(STORED AS DATE);

SELECT ESTDEPARTUREAIRPORT, CAST(STORED AS DATE) AS Date, COUNT(*) AS BROJPODATAKA FROM LETOVI_POLASCI GROUP BY ESTDEPARTUREAIRPORT, CAST(STORED AS DATE)
ORDER BY ESTDEPARTUREAIRPORT, CAST(STORED AS DATE);

SELECT ESTDEPARTUREAIRPORT, CAST(STORED AS DATE) AS Date, COUNT(*) AS DataCount FROM LETOVI_POLASCI WHERE ESTDEPARTUREAIRPORT = 'LOWW'
GROUP BY ESTDEPARTUREAIRPORT, CAST(STORED AS DATE) ORDER BY CAST(STORED AS DATE);

SELECT ESTDEPARTUREAIRPORT, COUNT(*) AS DataCount FROM LETOVI_POLASCI
WHERE CAST(STORED AS DATE) = '2022-11-04' GROUP BY ESTDEPARTUREAIRPORT ORDER BY ESTDEPARTUREAIRPORT;

