CREATE TABLE KORISNICI (
	IME VARCHAR(20) NOT NULL,
	PREZIME VARCHAR(20) NOT NULL,
	MAIL VARCHAR(40) NOT NULL,
	KORIME VARCHAR(20) NOT NULL,
	LOZINKA VARCHAR(40) NOT NULL, 
	PRIMARY KEY (MAIL),
);

GRANT SELECT, UPDATE, INSERT ON TABLE KORISNICI TO APLIKACIJA;